### ISSUE TITLE
Prevent concurrent calls `TimerFlowOf.unloadOrphaned`

### ISSUE THREAD

**Issue by rtar** [evolution-gaming/kafka-flow#157]
As `TimerFlowOf.unloadOrphaned` calls `persistence.flush` and resource cancellation could be a concurrent operation, there is a need to prevent this call to happen concurrently as the code underneath is not thread safe.

**Comment by nikitapecasa** [comment]
Do I get it right that code in question is the release [part](https://github.com/evolution-gaming/kafka-flow/blob/5c39e5e2a2de70b9007c8b1968b490ee2086ef4d/core/src/main/scala/com/evolutiongaming/kafka/flow/timer/TimerFlowOf.scala#L73) of the Resource?
And usage of `persistence.flush` in `def onTimer` is totally fine because it is triggered from within the `consumer.poll` loop?
Then I guess one of the options to fix is to somehow make sure that resource cancellation is always/most of the times triggered from `consumer.poll`?
I'm not an expert in the Resource yet, so might be saying some nonsense here :)

**Comment by nikitapecasa** [comment]
I think it is fixed now with the merge of https://github.com/evolution-gaming/kafka-flow/pull/229, a change was introduced ensuring that messages' processing is completed before execution of a TopicFlow's release
